name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --tag portfolio

    - name: Copy build output to host
      run: |
        docker run --name temp-container portfolio
        docker cp temp-container:/app/dist ./build
        docker rm temp-container

    - name: Deploy to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        source: "dist/*"
        target: "/var/www/html/portfolio"
